pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '^19.0.0'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm install'

- script: |
    npx eslint . --ext .es
  displayName: 'Lint'

- script: |
    yarn poi-util-transpile --source-map --replace
  displayName: 'Transpile to JavaScript'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: |
     **/*.*
     !.git/**/*
     !node_modules/**/*

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
